import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'
import fs from 'node:fs/promises'
import path from 'node:path'
import { flattenPaths } from './field-paths'
import { resolveSchemaPath, type WidgetOp } from './i864-widget-map'

/**
 * Fills the blank I-864 using pdf-lib's native form API.
 *
 * Key insight: pdf-lib strips the XFA wrapper on getForm(), which exposes
 * all 219 widgets as standard PDFTextField/PDFCheckBox/PDFDropdown. From
 * there it's the normal form-fill flow — no coordinate math, no viewer
 * regeneration dependency.
 *
 * We call form.updateFieldAppearances() at the end so every widget's
 * /AP stream is regenerated by pdf-lib itself, guaranteeing the text
 * renders in every viewer (Preview, Adobe, browsers, USCIS Lockbox).
 */
export async function fillI864(
  state: Record<string, unknown>
): Promise<Uint8Array> {
  const blankPath = path.join(process.cwd(), 'public', 'forms', 'i-864.pdf')
  const blankBytes = await fs.readFile(blankPath)
  const pdf = await PDFDocument.load(blankBytes, { ignoreEncryption: true })

  // Trigger XFA strip + expose fields as native pdf-lib types.
  const form = pdf.getForm()

  const applied: Array<{ path: string; widget: string; display: string }> = []
  const unresolved: string[] = []

  const flat = flattenPaths(state)
  for (const [schemaPath, value] of Object.entries(flat)) {
    const ops = resolveSchemaPath(schemaPath, value)
    if (ops.length === 0) {
      unresolved.push(schemaPath)
      continue
    }
    for (const op of ops) {
      const display = applyOp(form, op)
      if (display) {
        applied.push({ path: schemaPath, widget: op.name, display })
      } else {
        unresolved.push(`${schemaPath} -> ${op.name} (field not found / type mismatch)`)
      }
    }
  }

  // Regenerate all appearance streams so viewers don't need NeedAppearances.
  try {
    form.updateFieldAppearances()
  } catch (e) {
    console.error('updateFieldAppearances partial failure:', e)
  }

  // Build output doc: cover sheet + copied form pages (copyPages routes around
  // the XFA PDF's dangling page-tree refs that insertPage trips on).
  const out = await PDFDocument.create()
  const helv = await out.embedFont(StandardFonts.Helvetica)
  const helvBold = await out.embedFont(StandardFonts.HelveticaBold)

  const cover = out.addPage([612, 792])
  cover.drawText('FORMCUTTER - I-864 DRAFT', {
    x: 60,
    y: 730,
    size: 18,
    font: helvBold,
  })
  cover.drawText('Generated from uploaded documents + user chat. For reviewer inspection.', {
    x: 60,
    y: 708,
    size: 10,
    font: helv,
    color: rgb(0.3, 0.3, 0.3),
  })
  cover.drawText('Not a law firm. Not legal advice. Sign Part 8 only after accredited-rep review.', {
    x: 60,
    y: 694,
    size: 10,
    font: helv,
    color: rgb(0.6, 0.1, 0.1),
  })
  cover.drawText(new Date().toISOString(), {
    x: 60,
    y: 678,
    size: 9,
    font: helv,
    color: rgb(0.5, 0.5, 0.5),
  })

  let y = 640
  cover.drawText(`Filled fields (${applied.length}):`, {
    x: 60,
    y,
    size: 11,
    font: helvBold,
  })
  y -= 16
  for (const row of applied.slice(0, 35)) {
    if (y < 80) break
    cover.drawText(
      `${row.path.padEnd(50)} = ${truncate(row.display, 30)}`,
      { x: 60, y, size: 8, font: helv }
    )
    y -= 10
  }
  if (unresolved.length) {
    y -= 8
    cover.drawText(`Unresolved (${unresolved.length}): needs rep review`, {
      x: 60,
      y,
      size: 9,
      font: helvBold,
      color: rgb(0.6, 0.1, 0.1),
    })
    y -= 12
    for (const u of unresolved.slice(0, 10)) {
      if (y < 60) break
      cover.drawText(`  - ${truncate(u, 80)}`, {
        x: 60,
        y,
        size: 7,
        font: helv,
        color: rgb(0.4, 0.1, 0.1),
      })
      y -= 9
    }
  }

  const copied = await out.copyPages(pdf, pdf.getPageIndices())
  for (const p of copied) out.addPage(p)

  return await out.save()
}

// Apply one widget op; return a human-readable description of what happened,
// or null if the field couldn't be found or the type didn't match.
function applyOp(
  form: ReturnType<PDFDocument['getForm']>,
  op: WidgetOp
): string | null {
  try {
    if (op.kind === 'text') {
      const field = form.getTextField(op.name)
      field.setText(op.value)
      return op.value
    }
    if (op.kind === 'dropdown') {
      const field = form.getDropdown(op.name)
      const options = field.getOptions()
      // Prefer exact match; fall back to case-insensitive.
      const target = options.find((o) => o === op.value)
        ?? options.find((o) => o.toUpperCase() === op.value.toUpperCase())
      if (!target) return null
      field.select(target)
      return target
    }
    if (op.kind === 'checkbox') {
      const field = form.getCheckBox(op.name)
      if (op.checked) field.check()
      else field.uncheck()
      return op.checked ? '[x]' : '[ ]'
    }
    return null
  } catch (err) {
    console.error('applyOp error', op.name, err)
    return null
  }
}

function truncate(s: string, max: number): string {
  return s.length <= max ? s : s.slice(0, max - 1) + '...'
}
