/**
 * AUTO-GENERATED by scripts/generate-widget-map.mjs from the i-102 widget manifest.
 * DO NOT EDIT BY HAND — regenerate instead. Hand-written renderer logic lives
 * in i-102-widget-map.ts which imports from this file.
 */

export const AUTO_I_102_MAP: Record<string, string> = {
  "applicant.name.familyName": "form1[0].#subform[0].Pt1Line3a_FamilyName[0]",
  "applicant.name.givenName": "form1[0].#subform[0].Pt1Line3b_GivenName[0]",
  "applicant.name.middleName": "form1[0].#subform[0].Pt1Line3c_MiddleName[0]",
  "applicant.otherNames": "form1[0].#subform[0].Pt1Line4a_FamilyName[0]",
  "applicant.dateOfBirth": "form1[0].#subform[0].Pt1Line8_DateOfBirth[0]",
  "applicant.countryOfBirth": "form1[0].#subform[0].Pt1Line9_CountryOfBirth[0]",
  "applicant.countryOfCitizenship": "form1[0].#subform[0].Pt1Line10_CountryOfCitiz[0]",
  "applicant.aNumber": "form1[0].#subform[0].Pt1Line1_AlienNumber[0]",
  "applicant.ssn": "form1[0].#subform[1].Pt1Line11_SSN[0]",
  "applicant.gender": "MANUAL:enum",
  "applicant.mailingAddress.inCareOf": "form1[0].#subform[0].Pt1Line5a_InCareofName[0]",
  "applicant.mailingAddress.streetNumberAndName": "form1[0].#subform[0].Pt1Line4b_StreetNumberName[0]",
  "applicant.mailingAddress.cityOrTown": "form1[0].#subform[0].Pt1Line4d_CityOrTown[0]",
  "applicant.mailingAddress.state": "form1[0].#subform[0].Pt1Line4e_State[0]",
  "applicant.mailingAddress.zipCode": "form1[0].#subform[0].Pt1Line4f_ZipCode[0]",
  "applicant.daytimePhone": "form1[0].#subform[2].Pt4Line1_DaytimePhoneNumber1[0]",
  "applicant.mobilePhone": "form1[0].#subform[2].Pt4Line2_MobilePhoneNumber1[0]",
  "applicant.emailAddress": "form1[0].#subform[2].Pt4Line3_Email[0]",
  "applicant.passportNumber": "form1[0].#subform[1].Pt1Line18b_Passport[0]",
  "applicant.passportCountry": "form1[0].#subform[1].Pt1Line18d_CountryOfIssuance[0]",
  "applicant.passportExpirationDate": "form1[0].#subform[1].Pt1Line18e_ExpDate[0]",
  "applicant.dateOfLastEntry": "form1[0].#subform[1].Pt1Line12_DateLastAdmission[0]",
  "applicant.placeOfLastEntry": "form1[0].#subform[1].Pt1Line13_POE[0]",
  "applicant.i94Number": "form1[0].#subform[1].Pt1Line18a_ArrivalDeparture[0]",
  "applicant.classOfAdmission": "form1[0].#subform[1].Pt1Line14_ClassofAdmission[0]",
  "applicant.currentImmigrationStatus": "form1[0].#subform[1].Pt1Line16_NonimmigrantStatus[0]",
  "applicant.reasonForApplication": "MANUAL:enum",
  "signature.date": "form1[0].#subform[2].Pt4Line4_DateOfSignature[0]",
}
