/**
 * AUTO-GENERATED by scripts/generate-widget-map.mjs from the i-130 widget manifest.
 * DO NOT EDIT BY HAND — regenerate instead. Hand-written renderer logic lives
 * in i-130-widget-map.ts which imports from this file.
 */

export const AUTO_I_130_MAP: Record<string, string> = {
  "petitioner.name.familyName": "form1[0].#subform[0].Pt2Line4a_FamilyName[0]",
  "petitioner.name.givenName": "form1[0].#subform[0].Pt2Line4b_GivenName[0]",
  "petitioner.name.middleName": "form1[0].#subform[0].Pt2Line4c_MiddleName[0]",
  "petitioner.dateOfBirth": "form1[0].#subform[1].Pt2Line8_DateofBirth[0]",
  "petitioner.ssn": "form1[0].#subform[0].Pt2Line11_SSN[0]",
  "petitioner.aNumber": "form1[0].#subform[0].#area[4].Pt2Line1_AlienNumber[0]",
  "petitioner.mailingAddress.streetNumberAndName": "form1[0].#subform[1].Pt2Line10_StreetNumberName[0]",
  "petitioner.mailingAddress.cityOrTown": "form1[0].#subform[1].Pt2Line10_CityOrTown[0]",
  "petitioner.mailingAddress.state": "form1[0].#subform[1].Pt2Line10_State[0]",
  "petitioner.mailingAddress.zipCode": "form1[0].#subform[1].Pt2Line10_ZipCode[0]",
  "petitioner.countryOfBirth": "form1[0].#subform[1].Pt2Line7_CountryofBirth[0]",
  "petitioner.daytimePhone": "form1[0].#subform[8].Pt6Line3_DaytimePhoneNumber[0]",
  "petitioner.mobilePhone": "form1[0].#subform[8].Pt6Line4_MobileNumber[0]",
  "petitioner.emailAddress": "form1[0].#subform[8].Pt6Line5_Email[0]",
  "petitioner.maritalStatus": "MANUAL:enum",
  "petitioner.citizenshipStatus": "MANUAL:enum",
  "beneficiary.name.familyName": "form1[0].#subform[4].Pt4Line4a_FamilyName[0]",
  "beneficiary.name.givenName": "form1[0].#subform[4].Pt4Line4b_GivenName[0]",
  "beneficiary.name.middleName": "form1[0].#subform[4].Pt4Line4c_MiddleName[0]",
  "beneficiary.dateOfBirth": "form1[0].#subform[4].Pt4Line9_DateOfBirth[0]",
  "beneficiary.countryOfBirth": "form1[0].#subform[4].Pt4Line8_CountryOfBirth[0]",
  "beneficiary.aNumber": "form1[0].#subform[4].#area[6].Pt4Line1_AlienNumber[0]",
  "beneficiary.ssn": "form1[0].#subform[4].Pt4Line3_SSN[0]",
  "beneficiary.gender": "MANUAL:enum",
  "beneficiary.maritalStatus": "MANUAL:enum",
  "beneficiary.mailingAddress.streetNumberAndName": "form1[0].#subform[4].Pt4Line13_StreetNumberName[0]",
  "beneficiary.mailingAddress.cityOrTown": "form1[0].#subform[4].Pt4Line13_CityOrTown[0]",
  "beneficiary.mailingAddress.country": "form1[0].#subform[4].Pt4Line13_Country[0]",
  "relationship.type": "MANUAL:enum",
  "signature.date": "form1[0].#subform[8].Pt6Line6b_DateofSignature[0]",
}
