/**
 * AUTO-GENERATED by scripts/generate-widget-map.mjs from the i-485 widget manifest.
 * DO NOT EDIT BY HAND — regenerate instead. Hand-written renderer logic lives
 * in i-485-widget-map.ts which imports from this file.
 */

export const AUTO_I_485_MAP: Record<string, string> = {
  "applicant.name.familyName": "form1[0].#subform[0].Pt1Line1_FamilyName[0]",
  "applicant.name.givenName": "form1[0].#subform[0].Pt1Line1_GivenName[0]",
  "applicant.name.middleName": "form1[0].#subform[0].Pt1Line1_MiddleName[0]",
  "applicant.dateOfBirth": "form1[0].#subform[0].Pt1Line3_DOB[0]",
  "applicant.ssn": "form1[0].#subform[3].Pt1Line19_SSN[0]",
  "applicant.aNumber": "form1[0].#subform[0].AlienNumber[0]",
  "applicant.countryOfBirth": "form1[0].#subform[1].Pt1Line7_CountryOfBirth[0]",
  "applicant.countryOfCitizenship": "form1[0].#subform[1].Pt1Line8_CountryofCitizenshipNationality[0]",
  "applicant.mailingAddress.streetNumberAndName": "form1[0].#subform[2].Pt1Line18_CurrentStreetNumberName[0]",
  "applicant.mailingAddress.cityOrTown": "form1[0].#subform[2].Pt1Line18_CurrentCityOrTown[0]",
  "applicant.mailingAddress.state": "form1[0].#subform[2].Pt1Line18_CurrentState[0]",
  "applicant.mailingAddress.zipCode": "form1[0].#subform[2].Pt1Line18_CurrentZipCode[0]",
  "applicant.dateOfArrival": "form1[0].#subform[1].Pt1Line10_DateofArrival[0]",
  "applicant.i94Number": "form1[0].#subform[2].P1Line12_I94[0]",
  "applicant.gender": "MANUAL:enum",
  "applicant.maritalStatus": "MANUAL:enum",
  "applicant.daytimePhone": "form1[0].#subform[22].Pt3Line3_DaytimePhoneNumber1[0]",
  "applicant.emailAddress": "form1[0].#subform[22].Pt3Line5_Email[0]",
  "applicant.passportNumber": "form1[0].#subform[1].Pt1Line10_PassportNum[0]",
  "applicant.passportCountry": "form1[0].#subform[1].Pt1Line10_Passport[0]",
  "applicant.eligibilityCategory": "MANUAL:enum",
  "signature.date": "form1[0].#subform[22].Pt3Line7b_DateofSignature[0]",
}
