/**
 * AUTO-GENERATED by scripts/generate-widget-map.mjs from the i-589 widget manifest.
 * DO NOT EDIT BY HAND — regenerate instead. Hand-written renderer logic lives
 * in i-589-widget-map.ts which imports from this file.
 */

export const AUTO_I_589_MAP: Record<string, string> = {
  "applicant.name.familyName": "form1[0].#subform[0].PtAILine4_LastName[0]",
  "applicant.name.givenName": "form1[0].#subform[0].PtAILine5_FirstName[0]",
  "applicant.aNumber": "form1[0].#subform[0].PtAILine1_ANumber[0]",
  "applicant.dateOfBirth": "form1[0].#subform[0].DateTimeField1[0]",
  "applicant.countryOfBirth": "form1[0].#subform[0].TextField1[4]",
  "applicant.nationality": "form1[0].#subform[0].TextField1[3]",
  "applicant.ssn": "form1[0].#subform[0].TextField1[0]",
  "applicant.mailingAddress.streetNumberAndName": "form1[0].#subform[0].PtAILine9_StreetNumandName[0]",
  "applicant.mailingAddress.cityOrTown": "form1[0].#subform[0].PtAILine9_City[0]",
  "applicant.mailingAddress.state": "form1[0].#subform[0].PtAILine9_State[0]",
  "applicant.mailingAddress.zipCode": "form1[0].#subform[0].PtAILine9_ZipCode[0]",
  "applicant.gender": "MANUAL:enum",
  "applicant.maritalStatus": "MANUAL:enum",
  "applicant.lastEntryDate": "form1[0].#subform[0].DateTimeField2[0]",
  "applicant.i94Number": "form1[0].#subform[0].TextField3[0]",
  "applicant.passportNumber": "form1[0].#subform[0].TextField5[1]",
  "applicant.daytimePhone": "form1[0].#subform[0].PtAILine9_TelephoneNumbe[0]",
  "spouse.name.familyName": "form1[0].#subform[1].NotMarried[0].PtAIILine5_LastName[0]",
  "spouse.name.givenName": "form1[0].#subform[1].NotMarried[0].PtAIILine6_FirstName[0]",
  "spouse.dateOfBirth": "form1[0].#subform[1].NotMarried[0].DateTimeField7[0]",
  "spouse.aNumber": "form1[0].#subform[1].NotMarried[0].PtAIILine1_ANumber[0]",
  "signature.date": "form1[0].#subform[10].DateTimeField48[0]",
}
