/**
 * AUTO-GENERATED by scripts/generate-widget-map.mjs from the i-765 widget manifest.
 * DO NOT EDIT BY HAND — regenerate instead. Hand-written renderer logic lives
 * in i-765-widget-map.ts which imports from this file.
 */

export const AUTO_I_765_MAP: Record<string, string> = {
  "applicant.name.familyName": "form1[0].Page1[0].Line1a_FamilyName[0]",
  "applicant.name.givenName": "form1[0].Page1[0].Line1b_GivenName[0]",
  "applicant.name.middleName": "form1[0].Page1[0].Line1c_MiddleName[0]",
  "applicant.dateOfBirth": "form1[0].Page3[0].Line19_DOB[0]",
  "applicant.countryOfBirth": "form1[0].Page3[0].Line18c_CountryOfBirth[0]",
  "applicant.countryOfCitizenship": "form1[0].Page2[0].Line17a_CountryOfBirth[0]",
  "applicant.ssn": "form1[0].Page2[0].Line12b_SSN[0]",
  "applicant.aNumber": "form1[0].Page2[0].Line7_AlienNumber[0]",
  "applicant.i94Number": "form1[0].Page3[0].Line20a_I94Number[0]",
  "applicant.mailingAddress.streetNumberAndName": "form1[0].Page2[0].Line4b_StreetNumberName[0]",
  "applicant.mailingAddress.cityOrTown": "form1[0].Page2[0].Pt2Line5_CityOrTown[0]",
  "applicant.mailingAddress.state": "form1[0].Page2[0].Pt2Line5_State[0]",
  "applicant.mailingAddress.zipCode": "form1[0].Page2[0].Pt2Line5_ZipCode[0]",
  "applicant.gender": "MANUAL:enum",
  "applicant.maritalStatus": "MANUAL:enum",
  "applicant.dateOfLastEntry": "form1[0].Page3[0].Line21_DateOfLastEntry[0]",
  "applicant.placeOfLastEntry": "form1[0].Page3[0].place_entry[0]",
  "applicant.eligibilityCategory": "form1[0].Page3[0].#area[1].section_1[0]",
  "applicant.daytimePhone": "form1[0].Page4[0].Pt3Line3_DaytimePhoneNumber1[0]",
  "applicant.emailAddress": "form1[0].Page4[0].Pt3Line5_Email[0]",
  "signature.date": "form1[0].Page4[0].Pt3Line7b_DateofSignature[0]",
}
