/**
 * AUTO-GENERATED by scripts/generate-widget-map.mjs from the i-821 widget manifest.
 * DO NOT EDIT BY HAND — regenerate instead. Hand-written renderer logic lives
 * in i-821-widget-map.ts which imports from this file.
 */

export const AUTO_I_821_MAP: Record<string, string> = {
  "applicant.name.familyName": "form1[0].Page01[0].Part2_Item1_FamilyName[0]",
  "applicant.name.givenName": "form1[0].Page01[0].Part2_Item1_GivenName[0]",
  "applicant.name.middleName": "form1[0].Page01[0].Part2_Item1_MiddleName[0]",
  "applicant.dateOfBirth": "form1[0].Page02[0].Part2_Item10_DateOfBirth[0]",
  "applicant.countryOfBirth": "form1[0].Page02[0].Part2_Item14_CountryofBirth[0]",
  "applicant.countryOfCitizenship": "form1[0].Page02[0].Part2_Item16a[0]",
  "applicant.ssn": "form1[0].Page02[0].Part2_Item9_SocialSecurityNumber[0]",
  "applicant.aNumber": "form1[0].Page02[0].Part2_Item7_AlienNumber[0]",
  "applicant.i94Number": "form1[0].Page03[0].Part2_Item22_I94[0]",
  "applicant.mailingAddress.streetNumberAndName": "form1[0].Page02[0].Part2_Item4_StreetNumberName[0]",
  "applicant.mailingAddress.cityOrTown": "form1[0].Page02[0].Part2_Item4_CityOrTown[0]",
  "applicant.mailingAddress.state": "form1[0].Page02[0].Part2_Item4_State[0]",
  "applicant.mailingAddress.zipCode": "form1[0].Page02[0].Part2_Item4_ZipCode[0]",
  "applicant.dateOfLastEntry": "form1[0].Page03[0].P2_Line7_DateOfBirth[0]",
  "applicant.passportNumber": "form1[0].Page03[0].Part2_Item22_Passport[0]",
  "applicant.passportCountry": "form1[0].Page03[0].Part2_Item24_CountryofIssuance[0]",
  "applicant.daytimePhone": "form1[0].Page11[0].Part8_Item3_DayPhone[0]",
  "applicant.emailAddress": "form1[0].Page11[0].Part8_Item5_Email[0]",
  "signature.date": "form1[0].Page11[0].Part8_Item6b_DateofSignature[0]",
}
