/**
 * AUTO-GENERATED by scripts/generate-widget-map.mjs from the n-400 widget manifest.
 * DO NOT EDIT BY HAND — regenerate instead. Hand-written renderer logic lives
 * in n-400-widget-map.ts which imports from this file.
 */

export const AUTO_N_400_MAP: Record<string, string> = {
  "applicant.name.familyName": "form1[0].#subform[0].P2_Line1_FamilyName[0]",
  "applicant.name.givenName": "form1[0].#subform[0].P2_Line1_GivenName[0]",
  "applicant.name.middleName": "form1[0].#subform[0].P2_Line1_MiddleName[0]",
  "applicant.dateOfBirth": "form1[0].#subform[1].P2_Line8_DateOfBirth[0]",
  "applicant.ssn": "form1[0].#subform[1].Line12b_SSN[0]",
  "applicant.aNumber": "form1[0].#subform[0].#area[0].Line1_AlienNumber[0]",
  "applicant.countryOfBirth": "form1[0].#subform[1].P2_Line10_CountryOfBirth[0]",
  "applicant.mailingAddress.streetNumberAndName": "form1[0].#subform[2].P4_Line1_StreetName[0]",
  "applicant.mailingAddress.cityOrTown": "form1[0].#subform[2].P4_Line1_City[0]",
  "applicant.mailingAddress.state": "form1[0].#subform[2].P4_Line1_State[0]",
  "applicant.mailingAddress.zipCode": "form1[0].#subform[2].P4_Line1_ZipCode[0]",
  "applicant.dateBecameLPR": "form1[0].#subform[1].P2_Line9_DateBecamePermanentResident[0]",
  "applicant.gender": "MANUAL:enum",
  "applicant.maritalStatus": "MANUAL:enum",
  "applicant.daytimePhone": "form1[0].#subform[10].P12_Line3_Telephone[0]",
  "applicant.emailAddress": "form1[0].#subform[10].P12_Line5_Email[0]",
  "applicant.employerName": "form1[0].#subform[4].P5_EmployerName1[0]",
  "applicant.heightFeet": "form1[0].#subform[2].P7_Line3_HeightFeet[0]",
  "applicant.heightInches": "form1[0].#subform[2].P7_Line3_HeightInches[0]",
  "applicant.eyeColor": "MANUAL:enum",
  "applicant.hairColor": "MANUAL:enum",
  "applicant.ethnicity": "MANUAL:enum",
  "signature.date": "form1[0].#subform[10].P13_DateofSignature[0]",
}
